### ISSUE TITLE
Ephemery roadmap and tasks

### ISSUE THREAD

**Issue by taxmeifyoucan** [ephemery-testnet/ephemery-resources#1]
# Tracking issue for current state of Ephemery development

## Specifications

Specification was originally proposed in [this repository](https://github.com/ephemery-testnet/ephemery-resources/blob/master/specs.md) and now it's [drafted as EIP](https://github.com/ethereum/EIPs/blob/04369cb50ee6c1894dec868141e8a32e66dc4f16/EIPS/eip-testnet-draft.md).

- [ ] Validate the EIP specs draft
  - [ ] Explore feasibility of implementing it within clients based on clients architecture
  - [ ] Identify potential issues, contribute to spec and improve it
- [ ] Finish the draft, get EIP number 
  - [ ] Present at PEPP an EIP
  - [ ] Present at ACD

## Implementations

Reference implementation of the spec is done in bash. It's in separate repos for the [genesis](https://github.com/ephemery-testnet/ephemery-genesis/blob/master/scripts/build-genesis.sh) and [reset](https://github.com/ephemery-testnet/ephemery-scripts/blob/master/retention.sh) function.

There are also WIP implementations in [geth](https://github.com/ethereum/go-ethereum/compare/master...pk910:go-ethereum:ephemery-testnet) and [lodestar](https://github.com/ChainSafe/lodestar/compare/unstable...pk910:lodestar:ephemery-testnet). 

- [ ] Validate the reference implementation, explore potential improvements
- [ ] Contribute to existing WIP implementations 
- [ ] Create another implementation in a new client pair 
  - [ ] Each client should have it's 'Ephemery lib' or submodul 
- [ ] Ultimate goal is to have Ephemery network running on reference scripts + all client combos 

Main focus should be the genesis function which is the base support for Ephemery. Generating a genesis might require many new features in clients, creating new libraries to be included with them.

## Infrastructure

- Improving deployment methods
  - [ ] Improving the [docker setup ](https://github.com/ephemery-testnet/ephemery-scripts/tree/master/Docker)
  - [ ] Adding new deployment methods, e.g. ansible..
  - [ ] Adding Ephemery to existing deployment tools, e.g. Dappnode, stereum..
- [ ] Identify and add missing infrastructure (network monitoring, faucets,..)
- [ ] Contribute to auto-refund/deployment mechanisms 
- [ ] Grow pool of genesis validators 
- [ ] Create Ephemery website with reset countdown and project overview
- [ ] Improve docs, create tutorials

**Comment by puazgit** [comment]
selamat pagi
